#!/bin/zsh

pushd ../../semantics >/dev/null
kompile ctl-semantics.k
popd >/dev/null
echo "compiled..."
echo
rm -rf ctl-semantics-kompiled
cp -r ../../semantics/ctl-semantics-kompiled ./
krun ctl-test
